/*----------------------
 | probe_song.h
 | Description: Which tune the probe disc boots into. GENERATED by
 |   tools/assets/song_index.py from the id given to drums-chip.bat --
 |   do not hand-edit, the next run overwrites it.
 |   Currently: castle-halls.
 | Author: suinevere
 | Dependencies: N/A
 ----------------------*/
#ifndef PROBE_SONG
#define PROBE_SONG 0
#endif
