#!/usr/bin/env python3
"""Generate the synth's band-limited waveform tables as C data.

Built here rather than on the Saturn because the alternative is calling sin()
16384 times at boot through soft-float libm: several kilobytes of maths code
linked in, and the best part of a second of startup, to produce one kilobyte of
constants that never change.

A hard-edged square has infinitely many harmonics and every one above half the
playback rate folds back as an inharmonic whine -- the buzz that made the first
version sound like a PC speaker. Each waveform here is summed from a bounded
number of harmonics instead.
"""
import math, pathlib, sys

LEN = 256
HARMONICS = 16
NAMES = ["square", "pulse 25%", "triangle", "saw"]
AMP = 100.0


def build(kind):
    raw = []
    for i in range(LEN):
        phase = 2.0 * math.pi * i / LEN
        v = 0.0
        for h in range(1, HARMONICS + 1):
            if kind == 0:
                if h % 2 == 0:
                    continue
                amp = 1.0 / h
            elif kind == 1:
                amp = math.sin(h * math.pi * 0.25) / h
            elif kind == 2:
                if h % 2 == 0:
                    continue
                amp = (1.0 if h % 4 == 1 else -1.0) / float(h * h)
            else:
                amp = (1.0 if h % 2 else -1.0) / h
            v += amp * math.sin(h * phase)
        raw.append(v)
    peak = max(abs(x) for x in raw)
    return [max(-127, min(127, int(round(x * AMP / peak)))) for x in raw]


def main():
    out = pathlib.Path(sys.argv[1] if len(sys.argv) > 1
                       else "saturn/src/sound/synth_waves.c")
    body = []
    for k, name in enumerate(NAMES):
        body.append("    /* %s */" % name)
        table = build(k)
        for i in range(0, LEN, 16):
            body.append("    " + " ".join("%4d," % v for v in table[i:i + 16]))
    out.write_text('''/*----------------------
 | synth_waves.c
 | Description: The four band-limited waveform tables, generated by
 |   tools/assets/genwaves.py -- do not hand-edit. %(len)d samples each, summed
 |   from %(h)d harmonics so that notes played well above the table's own pitch do
 |   not alias into a buzz. Generated rather than computed at boot because the
 |   alternative links soft-float libm for constants that never change.
 | Author: suinevere
 ----------------------*/

/*----------------------
 | SYNTH_WAVE_TABLE
 | Description: square, 25%% pulse, triangle and saw, in the order the
 |   SYNTH_WAVE_* constants name them.
 | Author: suinevere
 ----------------------*/
const signed char SYNTH_WAVE_TABLE[4][%(len)d] = {
%(body)s
};
''' % {"len": LEN, "h": HARMONICS, "body": "\n".join(body)
       .replace("    /* square */", "  { /* square */")
       .replace("    /* pulse 25%", "  }, { /* pulse 25%")
       .replace("    /* triangle */", "  }, { /* triangle */")
       .replace("    /* saw */", "  }, { /* saw */") + "\n  }"},
        encoding="utf-8")
    print("wrote %s (%d bytes of table)" % (out, 4 * LEN))


if __name__ == "__main__":
    main()
