#!/usr/bin/env python3
"""/*----------------------
 | song_index.py
 | Description: Writes tools/scspprobe/src/probe_song.h, naming which tune the
 |     probe disc boots into. Turns a songs.json id into the index the emitted
 |     catalogue uses, which is its position in the manifest -- the one place
 |     that correspondence is written down, so nothing else has to know it.
 |
 |     Separate from drums-chip.bat because the script is a .bat and the lookup
 |     needs the manifest; and it fails on an unknown id before the build rather
 |     than after it, since the whole point of the probe is the thirty seconds.
 | Author: suinevere
 | Dependencies: json, pathlib, sys
 | Globals: N/A
 | Run: python tools/assets/song_index.py ID OUT.h   ("-" for the default)
 ----------------------*/"""
import json
import pathlib
import sys


def main(argv):
    """/*----------------------
     | main
     | Description: Resolves the id and writes the header.
     | Author: suinevere
     | Dependencies: json, pathlib
     | Globals: N/A
     | Params: argv -- [id, out_path]; id "-" means the manifest's default
     | Returns: 0, or 1 with a message naming every id there is
     ----------------------*/"""
    if len(argv) != 2:
        print("usage: song_index.py ID OUT.h", file=sys.stderr)
        return 1
    want, out = argv
    manifest = pathlib.Path(__file__).resolve().parent / "music" / "songs.json"
    doc = json.loads(manifest.read_text(encoding="utf-8"))
    ids = [s["id"] for s in doc["songs"]]
    if want == "-":
        want = doc.get("default", ids[0])
    if want not in ids:
        print("no song '%s' -- have: %s" % (want, ", ".join(ids)), file=sys.stderr)
        return 1
    index = ids.index(want)
    pathlib.Path(out).write_text(
        "/*----------------------\n"
        " | probe_song.h\n"
        " | Description: Which tune the probe disc boots into. GENERATED by\n"
        " |   tools/assets/song_index.py from the id given to drums-chip.bat --\n"
        " |   do not hand-edit, the next run overwrites it.\n"
        " |   Currently: %s.\n"
        " | Author: suinevere\n"
        " | Dependencies: N/A\n"
        " ----------------------*/\n"
        "#ifndef PROBE_SONG\n"
        "#define PROBE_SONG %d\n"
        "#endif\n" % (want, index), encoding="utf-8")
    print("probe boots into %s (song %d of %d)" % (want, index, len(ids)))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
