server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;

        server_name suinevere.duckdns.org;

        # Keep ACME challenge local for Certbot verification
        location /.well-known/acme-challenge/ {
                root /var/www/html;
        }

        location /zork {
#           try_files /zork.netbin =404;
            try_files $uri $uri/ =404;
                # Match any .netbin file inside /zork
#               location ~* \.netbin$ {

                proxy_http_version 1.1;
                sendfile off;
                send_timeout 600s;
                keepalive_timeout 300s 300s;
                gzip off;
                default_type application/x-planetweb-app-segasaturn;
                   add_header Content-Disposition 'attachment; filename=zork';
            add_header Cache-Control "no-store, no-cache, must-revalidate";
#               }
        }

        # Proxy all other traffic to GitHub Pages
        location / {
                proxy_pass https://suinevere.github.io/suinevere-site/;

                proxy_set_header Host suinevere.github.io;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;

                proxy_ssl_server_name on;
                proxy_ssl_protocols TLSv1.2 TLSv1.3;
        }
}

server {
    root /var/www/html;

    listen 443 ssl default_server; # managed by Certbot
    listen [::]:443 ssl default_server;
    server_name suinevere.duckdns.org;

    ssl_certificate /etc/letsencrypt/live/suinevere.duckdns.org/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/suinevere.duckdns.org/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

    location /zork {
             try_files $uri $uri/ =404;
#            try_files /zork.netbin =404;

           # Match any .netbin file inside /zork
           location ~* \.netbin$ {
               default_type application/octet-stream;
               add_header Content-Disposition 'attachment';
               add_header Cache-Control "no-store, no-cache, must-revalidate";
           }
        }

    location / {
        proxy_pass https://suinevere.github.io/suinevere-site/;

        proxy_set_header Host suinevere.github.io;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_ssl_server_name on;
        proxy_ssl_protocols TLSv1.2 TLSv1.3;
    }
}
