/*----------------------
 | cues.h
 | Description: Runtime lookup for the situational CD-DA cues generated by
 |   tools/gen_cues.py -- the tracks the original console release played over a
 |   room's own theme when a villain was in it, when the sword said one was
 |   near, when something was picked up, and at the two endings. A game with no
 |   row offers no cues and every lookup here answers 0, which every caller
 |   reads as "leave the room's own music alone".
 |     game_cues.inc is included only by cues.c, the way presentation.c alone
 |   includes game_presentation.inc; the two record types callers need are
 |   declared below instead, guarded on CUE_GAME_N so that the one translation
 |   unit where both meet does not redeclare them. They must stay
 |   byte-identical to the .inc's own.
 | Author: suinevere
 | Dependencies: engine/room_model.h (RoomModel)
 ----------------------*/
#ifndef CUES_H
#define CUES_H

#include "room_model.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifndef CUE_GAME_N
typedef struct {
    unsigned short villain;
    unsigned short room;
    unsigned char  track;
    unsigned char  unseen;
} CueRule;
typedef struct {
    unsigned short release;
    const char *serial;
    const CueRule *rules;
    unsigned char  nrules;
    unsigned char  invisible;
    unsigned short sword;
    unsigned char  danger;
    unsigned char  take;
    unsigned char  death;
    unsigned char  win;
} GameCueMap;
#endif /* CUE_GAME_N */

/*----------------------
 | cue_game_index
 | Description: The GAME_CUE_MAP row for one game, by release and 6-char
 |   serial. The one call a caller needs to ask "does this story have cues at
 |   all".
 | Author: suinevere
 | Dependencies: game_cues.inc
 | Globals: GAME_CUE_MAP
 | Params: release -- Z-machine release; serial -- 6-char serial, not
 |   guaranteed NUL-terminated
 | Returns: the row index, or -1 when the game has no cues
 ----------------------*/
int cue_game_index(unsigned int release, const char *serial);

/*----------------------
 | cue_track
 | Description: The cue track for the turn the snapshot describes, or 0 for
 |   none. Rules are tried in order and the first match wins, which is how the
 |   original's "a troll in the room outranks a thief in it" falls out without
 |   a second condition: the troll's rule is reached first.
 |
 |   A rule matches when its villain is among the room's objects, the rule's
 |   room is this one (or the rule names no room), and -- for a villain the
 |   story can hide, which is the thief and only the thief -- the invisible
 |   attribute is clear. With no rule matching, the sword speaks instead: if the
 |   player is carrying it and any rule's villain is standing in a room this one
 |   has an open exit to, the danger track plays. That is the Z-machine
 |   equivalent of the original's sword-glow level 1; level 2, a villain in this
 |   room, is what the rules above already answer.
 | Author: suinevere
 | Dependencies: game_cues.inc, room_model.h (room_model_object_attr,
 |   room_model_object_parent)
 | Globals: GAME_CUE_MAP
 | Params: release, serial -- the story identity; m -- this prompt's snapshot
 | Returns: a CD-DA track number, or 0 when no cue applies
 ----------------------*/
int cue_track(unsigned int release, const char *serial, const RoomModel *m);

/*----------------------
 | cue_take_track / cue_death_track / cue_win_track
 | Description: The three cues that are not about where the player is standing
 |   -- the one-shot a successful take arms, and the two endings. Each returns 0
 |   when the game has no row or does not offer that cue.
 | Author: suinevere
 | Dependencies: game_cues.inc
 | Globals: GAME_CUE_MAP
 | Params: release, serial -- the story identity
 | Returns: a CD-DA track number, or 0
 ----------------------*/
int cue_take_track(unsigned int release, const char *serial);
int cue_death_track(unsigned int release, const char *serial);
int cue_win_track(unsigned int release, const char *serial);

#ifdef __cplusplus
}
#endif
#endif /* CUES_H */
