/*----------------------
 | presentation.h
 | Description: Runtime lookup for the per-room presentation table generated by
 |   tools/gen_presentation.py -- the picture, CD-DA track and sound-effect bank
 |   the original console release used for one room of one game. Games without a
 |   table show no picture at all; there is no other art route left.
 |     game_presentation.inc itself is included only by presentation.c, the way
 |   presentation.c alone includes it -- its 256-entry
 |   room table, IMAGE_FRAME and PRES_AREA have no business being copied into
 |   every translation unit that just wants to call pres_of_room. What every
 |   caller does need -- the three record types and the two counts a caller can
 |   size an array or a loop against -- are declared below instead, copied by
 |   hand from the .inc and required to stay byte-identical to it (a generator
 |   run that changes them has to update both).
 |     The block is guarded on PRES_FRAME_N rather than unconditional: when
 |   presentation.c includes game_presentation.inc ahead of this header (the
 |   only place both ever meet), the .inc's own typedefs and counts have
 |   already landed and redeclaring them here would conflict -- a
 |   typedef-of-an-anonymous-struct is a distinct type on every occurrence,
 |   even with identical members, so "harmless duplicate" is not available the
 |   way it is for a #define.
 | Author: suinevere
 | Dependencies: N/A
 ----------------------*/
#ifndef PRESENTATION_H
#define PRESENTATION_H

#ifdef __cplusplus
extern "C" {
#endif

#ifndef PRES_FRAME_N
typedef struct {
    unsigned char image;
    unsigned char track;
    unsigned char se_bank;
} Presentation;
typedef struct {
    unsigned char area;
    unsigned long offset;
    unsigned long length;
} PresFrame;
typedef struct {
    unsigned short release;
    const char *serial;
    const Presentation *rooms;
    unsigned char map_bg;
} GamePresMap;

/*----------------------
 | PRES_FRAME_N / PRES_AREA_N / PRES_MAP_BG_N
 | Description: The frame, area-archive and map-sheet counts from
 |   game_presentation.inc, copied here so a caller (or a test) can size against
 |   them without pulling in the table itself. Must equal the .inc's own, which
 |   saturn/tests/test_presentation_counts.py is what actually holds them to --
 |   they grow every time a generated picture is added to the supply.
 | Author: suinevere
 ----------------------*/
#define PRES_FRAME_N 75
#define PRES_AREA_N 12
#define PRES_MAP_BG_N 4
#endif /* PRES_FRAME_N */

/*----------------------
 | pres_game_index
 | Description: The GAME_PRES_MAP row for one game, by release and 6-char
 |   serial. The one call a caller needs to ask "does this story have an
 |   authored presentation at all".
 | Author: suinevere
 | Dependencies: string.h (memcmp), game_presentation.inc
 | Globals: GAME_PRES_MAP
 | Params: release -- Z-machine release; serial -- 6-char serial, not
 |   guaranteed NUL-terminated
 | Returns: the row index, or -1 when the game has no table
 ----------------------*/
int pres_game_index(unsigned int release, const char *serial);

/*----------------------
 | pres_of_room
 | Description: The authored presentation for one room. Fills *out and returns 1
 |   only when the room carries a picture; a room with no entry leaves *out
 |   untouched and returns 0, which every caller reads as "hold what is showing"
 |   rather than "show nothing".
 | Author: suinevere
 | Dependencies: game_presentation.inc
 | Globals: GAME_PRES_MAP
 | Params: release, serial -- the story identity; obj -- the room's object
 |   number; out -- filled on success
 | Returns: 1 when the room is authored, 0 otherwise
 ----------------------*/
int pres_of_room(unsigned int release, const char *serial, unsigned int obj,
                 Presentation *out);

/*----------------------
 | pres_frame
 | Description: Where one image's record lies inside its archive. The offset is
 |   generated rather than walked because a CGL record's end is only discovered
 |   by decompressing it, so reaching a late frame by walking would cost every
 |   earlier frame in the archive. Any of the outputs may be null.
 | Author: suinevere
 | Dependencies: game_presentation.inc
 | Globals: IMAGE_FRAME
 | Params: image -- 1-based image index; area, offset, length -- filled on
 |   success when non-null
 | Returns: 1 on success, 0 when image is out of range
 ----------------------*/
int pres_frame(int image, int *area, unsigned long *offset, unsigned long *length);

/*----------------------
 | pres_area_name
 | Description: The 4-character archive stem for one area, for building the disc
 |   path.
 | Author: suinevere
 | Dependencies: game_presentation.inc
 | Globals: PRES_AREA
 | Params: area -- 0..PRES_AREA_N-1
 | Returns: the stem, or NULL when area is out of range
 ----------------------*/
const char *pres_area_name(int area);

/*----------------------
 | pres_map_bg
 | Description: The /TGA filename of the sheet one game's map page is drawn on.
 |   Which sheet is a property of the game's genre -- a ship's log for the
 |   science fiction, ruled ledger paper for the mysteries, parchment for the
 |   fantasies -- decided in tools/game_genre.py and generated into the table
 |   beside the room rows, because the runtime has no other way to know what
 |   kind of story it is running.
 |     Never returns NULL. A story with no table at all, or a row naming a sheet
 |   that is not there, answers the default parchment: the map page has drawn on
 |   that since before any of the others existed, so falling back to it cannot
 |   be a regression for any game.
 | Author: suinevere
 | Dependencies: game_presentation.inc
 | Globals: GAME_PRES_MAP, PRES_MAP_BG
 | Params: release -- Z-machine release; serial -- 6-char serial
 | Returns: a bare /TGA filename
 ----------------------*/
const char *pres_map_bg(unsigned int release, const char *serial);

#ifdef __cplusplus
}
#endif
#endif /* PRESENTATION_H */
