/*----------------------
 | presentation.h
 | Description: Runtime lookup for the per-room presentation table generated by
 |   tools/gen_presentation.py -- the picture, CD-DA track and sound-effect bank
 |   the original console release used for one room of one game. Games without a
 |   table are unaffected and keep the scene path in scene_map.h.
 | Author: suinevere
 | Dependencies: game_presentation.inc
 ----------------------*/
#ifndef PRESENTATION_H
#define PRESENTATION_H

#ifdef __cplusplus
extern "C" {
#endif

#include "game_presentation.inc"

/*----------------------
 | pres_game_index
 | Description: The GAME_PRES_MAP row for one game, by release and 6-char
 |   serial. The one call a caller needs to ask "does this story have an
 |   authored presentation at all".
 | Author: suinevere
 | Dependencies: string.h (memcmp), game_presentation.inc
 | Globals: GAME_PRES_MAP
 | Params: release -- Z-machine release; serial -- 6-char serial, not
 |   guaranteed NUL-terminated
 | Returns: the row index, or -1 when the game has no table
 ----------------------*/
int pres_game_index(unsigned int release, const char *serial);

/*----------------------
 | pres_of_room
 | Description: The authored presentation for one room. Fills *out and returns 1
 |   only when the room carries a picture; a room with no entry leaves *out
 |   untouched and returns 0, which every caller reads as "hold what is showing"
 |   rather than "show nothing".
 | Author: suinevere
 | Dependencies: game_presentation.inc
 | Globals: GAME_PRES_MAP
 | Params: release, serial -- the story identity; obj -- the room's object
 |   number; out -- filled on success
 | Returns: 1 when the room is authored, 0 otherwise
 ----------------------*/
int pres_of_room(unsigned int release, const char *serial, unsigned int obj,
                 Presentation *out);

/*----------------------
 | pres_frame
 | Description: Where one image's record lies inside its archive. The offset is
 |   generated rather than walked because a CGL record's end is only discovered
 |   by decompressing it, so reaching a late frame by walking would cost every
 |   earlier frame in the archive. Any of the outputs may be null.
 | Author: suinevere
 | Dependencies: game_presentation.inc
 | Globals: IMAGE_FRAME
 | Params: image -- 1-based image index; area, offset, length -- filled on
 |   success when non-null
 | Returns: 1 on success, 0 when image is out of range
 ----------------------*/
int pres_frame(int image, int *area, unsigned long *offset, unsigned long *length);

/*----------------------
 | pres_area_name
 | Description: The 4-character archive stem for one area, for building the disc
 |   path.
 | Author: suinevere
 | Dependencies: game_presentation.inc
 | Globals: PRES_AREA
 | Params: area -- 0..PRES_AREA_N-1
 | Returns: the stem, or NULL when area is out of range
 ----------------------*/
const char *pres_area_name(int area);

#ifdef __cplusplus
}
#endif
#endif /* PRESENTATION_H */
