/*----------------------
 | scene_map.h
 | Description: Runtime lookup for the per-game scene tables generated by
 |   tools/gen_scene_tables.py -- the SC_* vocabulary, and the room and track
 |   accessors that replace keyword classification for games with an authored
 |   scene map.
 | Author: suinevere
 | Dependencies: N/A
 ----------------------*/
#ifndef SCENE_MAP_H
#define SCENE_MAP_H

#ifdef __cplusplus
extern "C" {
#endif

/* GENERATED SCENE ENUM -- BEGIN. Written by tools/gen_scene_tables.py; do not edit. */
#define SCENE_N 32
#define GAME_N 31
enum {
    SC_FOREST = 0,
    SC_GARDEN = 1,
    SC_DESERT = 2,
    SC_ROCKY = 3,
    SC_SHORE = 4,
    SC_RIVER = 5,
    SC_ROAD = 6,
    SC_CAVE = 7,
    SC_MAZE = 8,
    SC_MINE = 9,
    SC_PIT = 10,
    SC_CRYPT = 11,
    SC_HOUSE_EXT = 12,
    SC_VILLAGE = 13,
    SC_CASTLE = 14,
    SC_DOCK = 15,
    SC_PARLOR = 16,
    SC_KITCHEN = 17,
    SC_BEDROOM = 18,
    SC_BATHROOM = 19,
    SC_LIBRARY = 20,
    SC_DARKROOM = 21,
    SC_CORRIDOR = 22,
    SC_OFFICE = 23,
    SC_LAB = 24,
    SC_STORAGE = 25,
    SC_CELL = 26,
    SC_THEATER = 27,
    SC_TEMPLE = 28,
    SC_SHIP_EXT = 29,
    SC_SHIP_INT = 30,
    SC_SPACE = 31,
};
static const char *const SCENE_NAME[SCENE_N] = {
    "FOREST",
    "GARDEN",
    "DESERT",
    "ROCKY",
    "SHORE",
    "RIVER",
    "ROAD",
    "CAVE",
    "MAZE",
    "MINE",
    "PIT",
    "CRYPT",
    "HOUSE_EXT",
    "VILLAGE",
    "CASTLE",
    "DOCK",
    "PARLOR",
    "KITCHEN",
    "BEDROOM",
    "BATHROOM",
    "LIBRARY",
    "DARKROOM",
    "CORRIDOR",
    "OFFICE",
    "LAB",
    "STORAGE",
    "CELL",
    "THEATER",
    "TEMPLE",
    "SHIP_EXT",
    "SHIP_INT",
    "SPACE",
};
/* GENERATED SCENE ENUM -- END */

/*----------------------
 | scene_of_room
 | Description: The scene authored for one room of one game. Matches a
 |   GAME_ROOM_MAP row by release and 6-char serial, then indexes that game's
 |   256-byte map by the room's object number. Returns -1 when the game is
 |   unknown or the room carries no scene, which the caller treats as "hold
 |   whatever is showing".
 | Author: suinevere
 | Dependencies: string.h (memcmp), game_rooms.inc
 | Globals: GAME_ROOM_MAP
 | Params: release -- Z-machine release; serial -- 6-char serial, not
 |   guaranteed NUL-terminated; obj -- the room's object number
 | Returns: an SC_* value, or -1
 ----------------------*/
int scene_of_room(unsigned int release, const char *serial, unsigned int obj);

/*----------------------
 | scene_game_index
 | Description: The GAME_ROOM_MAP row for one game, by release and 6-char
 |   serial.
 | Author: suinevere
 | Dependencies: string.h (memcmp), game_rooms.inc
 | Globals: GAME_ROOM_MAP
 | Params: release -- Z-machine release; serial -- 6-char serial, not
 |   guaranteed NUL-terminated
 | Returns: the row index into GAME_ROOM_MAP and SCENE_TRACKS, or -1 when the
 |   game is unlisted
 ----------------------*/
int scene_game_index(unsigned int release, const char *serial);

/*----------------------
 | scene_name
 | Description: The display name for one SC_* scene, for tests and the
 |   options UI.
 | Author: suinevere
 | Dependencies: N/A
 | Globals: SCENE_NAME
 | Params: scene -- an SC_* value
 | Returns: the scene's name, or NULL when scene is out of range
 ----------------------*/
const char *scene_name(int scene);

/*----------------------
 | scene_track_mask
 | Description: The authored track mask for one scene, shared by every game.
 |   A zero mask means no tracks were authored, which the caller treats as
 |   "fall back to the neutral pool".
 | Author: suinevere
 | Dependencies: game_tracks.inc
 | Globals: SCENE_TRACKS
 | Params: scene -- an SC_* value
 | Returns: the track mask, or 0 when the scene is out of range or unauthored
 ----------------------*/
unsigned long scene_track_mask(int scene);

#ifdef __cplusplus
}
#endif
#endif /* SCENE_MAP_H */
