/* GENERATED SCENE ENUM -- BEGIN. Written by tools/gen_scene_tables.py; do not edit. */
#define SCENE_N 32
#define GAME_N 31
enum {
    SC_FOREST = 0,
    SC_GARDEN = 1,
    SC_DESERT = 2,
    SC_ROCKY = 3,
    SC_SHORE = 4,
    SC_RIVER = 5,
    SC_ROAD = 6,
    SC_CAVE = 7,
    SC_MAZE = 8,
    SC_MINE = 9,
    SC_PIT = 10,
    SC_CRYPT = 11,
    SC_HOUSE_EXT = 12,
    SC_VILLAGE = 13,
    SC_CASTLE = 14,
    SC_DOCK = 15,
    SC_PARLOR = 16,
    SC_KITCHEN = 17,
    SC_BEDROOM = 18,
    SC_BATHROOM = 19,
    SC_LIBRARY = 20,
    SC_DARKROOM = 21,
    SC_CORRIDOR = 22,
    SC_OFFICE = 23,
    SC_LAB = 24,
    SC_STORAGE = 25,
    SC_CELL = 26,
    SC_THEATER = 27,
    SC_TEMPLE = 28,
    SC_SHIP_EXT = 29,
    SC_SHIP_INT = 30,
    SC_SPACE = 31,
};
static const char *const SCENE_NAME[SCENE_N] = {
    "FOREST",
    "GARDEN",
    "DESERT",
    "ROCKY",
    "SHORE",
    "RIVER",
    "ROAD",
    "CAVE",
    "MAZE",
    "MINE",
    "PIT",
    "CRYPT",
    "HOUSE_EXT",
    "VILLAGE",
    "CASTLE",
    "DOCK",
    "PARLOR",
    "KITCHEN",
    "BEDROOM",
    "BATHROOM",
    "LIBRARY",
    "DARKROOM",
    "CORRIDOR",
    "OFFICE",
    "LAB",
    "STORAGE",
    "CELL",
    "THEATER",
    "TEMPLE",
    "SHIP_EXT",
    "SHIP_INT",
    "SPACE",
};
/* GENERATED SCENE ENUM -- END */
