#!/usr/bin/env python3
"""Convert binary files into a single C source of byte arrays.

Emits arrays guarded by #ifdef NETBIN so the generated file compiles to an
empty object in the CD build, which globs every src/*.c unconditionally.

Usage:
    python3 tools/gen_blob.py OUT.c NAME=PATH [NAME=PATH ...]
"""
import sys


def emit_array(name, data):
    out = [f"const unsigned char netbin_{name}_bytes[{len(data)}] = {{"]
    for i in range(0, len(data), 16):
        out.append("    " + "".join(f"0x{b:02x}," for b in data[i:i + 16]))
    out.append("};")
    out.append(f"const unsigned int netbin_{name}_len = {len(data)}u;")
    out.append("")
    out.append(f"const unsigned char *netbin_{name}_data(void)"
               f" {{ return netbin_{name}_bytes; }}")
    out.append(f"unsigned int         netbin_{name}_size(void)"
               f" {{ return netbin_{name}_len; }}")
    return "\n".join(out)


def emit_stub(name):
    return "\n".join([
        f"const unsigned char *netbin_{name}_data(void) {{ return 0; }}",
        f"unsigned int         netbin_{name}_size(void) {{ return 0u; }}",
    ])


def main(argv):
    if len(argv) < 3:
        sys.stderr.write(__doc__)
        return 2
    out_path, specs = argv[1], argv[2:]

    names = []
    for spec in specs:
        if "=" not in spec:
            sys.stderr.write(f"gen_blob: bad spec {spec!r}, want NAME=PATH\n")
            return 2
        names.append(spec.split("=", 1))

    parts = [
        "/* GENERATED by tools/gen_blob.py -- do not edit by hand. */",
        '#include "netbin_story.h"',
        "",
        "#ifdef NETBIN",
        "",
    ]
    for name, path in names:
        with open(path, "rb") as f:
            data = f.read()
        parts.append(emit_array(name, data))
        parts.append("")
    parts.append("#else")
    parts.append("")
    for name, _ in names:
        parts.append(emit_stub(name))
        parts.append("")
    parts.append("#endif /* NETBIN */")

    with open(out_path, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(parts) + "\n")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
