/*----------------------
 | music_synth_data.h
 | Description: The tunes the synth can play, in both builds. Data only: the
 |   engine reads it and never reaches back. Generated by
 |   tools/assets/mid2pat.py from tools/assets/music/songs.json -- do not
 |   hand-edit, because the .c asserts its own array lengths against the
 |   numbers here.
 |
 |   The catalogue, in emit order:
 |     disc castle-halls Shadowgate, Entryway       castle-halls.mid, a fan sequence; drums authored separately in 3/4
 |     net  title        Shadowgate, Title Screen   sgtitle.mid, a fan sequence of Shadowgate (NES, 1989), music by Hiroyuki Masuno
 |     net  halls        Shadowgate, Hall of Mirrors sghalls.mid, a fan sequence of Shadowgate (NES, 1989), music by Hiroyuki Masuno
 |     net  banquet      Shadowgate, Banquet Hall   sgbanqet.mid, a fan sequence of Shadowgate (NES, 1989), music by Hiroyuki Masuno
 |     net  court        Shadowgate, Courtyard      sgcourt.mid, a fan sequence of Shadowgate (NES, 1989), music by Hiroyuki Masuno
 |     net  dragon       Shadowgate, Dragon's Den   sgdragon.mid, a fan sequence of Shadowgate (NES, 1989), music by Hiroyuki Masuno
 |     net  lake         Shadowgate, Subterranean Cavern sglake.mid, a fan sequence of Shadowgate (NES, 1989), music by Hiroyuki Masuno
 |     net  corridor     Shadowgate, Twilight       sglitrod.mid, a fan sequence of Shadowgate (NES, 1989), music by Hiroyuki Masuno
 |     net  mirror       Shadowgate, sgmirror (unidentified) sgmirror.mid, a fan sequence of Shadowgate (NES, 1989), music by Hiroyuki Masuno
 |     net  overworld    Shadowgate, Game Over      sgover.mid, a fan sequence of Shadowgate (NES, 1989), music by Hiroyuki Masuno
 |     net  shadow7      Shadowgate, Subterranean Cavern shadow7.mid, a fan sequence of Shadowgate (NES, 1989), music by Hiroyuki Masuno
 |     net  shadow8      Shadowgate, Danger         shadow8.mid, a fan sequence of Shadowgate (NES, 1989), music by Hiroyuki Masuno
 |
 |   Default: Shadowgate, Entryway.
 | Author: suinevere
 | Dependencies: tracker.h
 ----------------------*/
#ifndef MUSIC_SYNTH_DATA_H
#define MUSIC_SYNTH_DATA_H

#include "tracker.h"

#ifdef __cplusplus
extern "C" {
#endif

/*----------------------
 | MUSIC_SYNTH_SONGS_CD
 | Description: How many tunes the CD build carries, which is fewer, and why
 |   there are two counts at all.
 |
 |   The catalogue is pattern data in .rodata, and on the CD target
 |   __heap_start follows .rodata: every byte of music comes straight off the
 |   HWRAM heap the story is loaded into. Measured, the full catalogue is 55,424
 |   bytes and takes that heap to 98,016, which is below the 129,704 bytes
 |   LURKING.Z3 needs to load at all -- the disc's largest story simply stops
 |   working. The netbin loads no story and has 130 KB of its own image budget
 |   spare, so it carries all of them.
 |
 |   The CD build's tunes are the first MUSIC_SYNTH_SONGS_CD of the catalogue,
 |   never a scattered subset, so both builds read the same prefix of the same
 |   two arrays and a song index means the same thing in each. Which tunes those
 |   are is the "cd": true flag in songs.json.
 |
 |   This costs the CD build nothing it had: the synth is its fallback for a
 |   disc that carries no CD-DA, and a disc that does carry it has thirty-one
 |   real tracks and never reaches here.
 | Author: suinevere
 ----------------------*/
#define MUSIC_SYNTH_SONGS_CD 1

/*----------------------
 | MUSIC_SYNTH_SONGS / MUSIC_SYNTH_ROWS / MUSIC_SYNTH_CHANNELS
 | Description: How many tunes this build has and the shape of a pattern. Every
 |   tune shares the row and channel counts, because the tracker reads them off
 |   the song it is given and a tune with a shape of its own would only mean a
 |   second set of numbers to keep in step.
 | Author: suinevere
 ----------------------*/
#ifdef NETBIN
#define MUSIC_SYNTH_SONGS    12
#else
#define MUSIC_SYNTH_SONGS    MUSIC_SYNTH_SONGS_CD
#endif
#define MUSIC_SYNTH_ROWS     16
#define MUSIC_SYNTH_CHANNELS 4

/*----------------------
 | MUSIC_SYNTH_CELLS / MUSIC_SYNTH_ORDER
 | Description: The lengths of the two flat arrays every tune points into. They
 |   are here rather than only in the .c because the file asserts its own
 |   initialiser lengths against them at compile time: C zero-fills a short
 |   initialiser without complaint, which would be a silently truncated
 |   catalogue that every test still passes -- and with two builds carrying
 |   different lengths, that assertion is now also what catches a prefix cut in
 |   the wrong place.
 | Author: suinevere
 ----------------------*/
#ifdef NETBIN
#define MUSIC_SYNTH_CELLS    19904
#define MUSIC_SYNTH_ORDER    569
#else
#define MUSIC_SYNTH_CELLS    1088
#define MUSIC_SYNTH_ORDER    24
#endif

/*----------------------
 | MUSIC_SYNTH_PAIRS
 | Description: How many distinct (note, wv) pairs the whole catalogue uses, and
 |   so how long the table every cell indexes is.
 |
 |   Outside the #if above, unlike the cell and order counts. Those are cut to a
 |   prefix on the CD target because that build links one tune; this one is not,
 |   because that build still plays the other eleven off /BG/MUSIC.PAT and their
 |   cells are indices into the whole table. Cut it to the CD prefix and every
 |   disc tune reads pairs that are not there.
 | Author: suinevere
 ----------------------*/
#define MUSIC_SYNTH_PAIRS    182

/*----------------------
 | MUSIC_SYNTH_DEFAULT
 | Description: The tune played where nothing has chosen one -- the boot menus,
 |   the netbin, and any CD-DA track the mood table does not reach.
 | Author: suinevere
 ----------------------*/
#define MUSIC_SYNTH_DEFAULT  0

/*----------------------
 | MUSIC_PAT_FILE / MUSIC_PAT_HEADER_BYTES / MUSIC_PAT_SLOT_BYTES
 | Description: The disc copy of this catalogue, and the two sizes a loader has
 |   to know before it has read anything.
 |
 |   The CD build carries only the first MUSIC_SYNTH_SONGS_CD tunes in .rodata
 |   and reads the rest out of /BG/MUSIC.PAT one at a time. That is not a
 |   convenience: on that target __heap_start follows .rodata, so a linked tune
 |   comes straight out of the heap the story is loaded into, and the whole
 |   catalogue there stopped the disc's largest story loading at all. A tune on
 |   the disc costs Low Work RAM instead, which the story does not use.
 |
 |   One at a time and not all at once, also measured: the catalogue is bigger
 |   than the Low Work RAM left in the worst in-game case, and one slot the size
 |   of the largest tune is not.
 |
 |   HEADER_BYTES is what the loader reads of the first sector -- the directory,
 |   the track table and the ids -- and the generator refuses to write a header
 |   longer than it. SLOT_BYTES is the largest tune's record padded to whole
 |   sectors, which is the buffer every tune is read into.
 | Author: suinevere
 ----------------------*/
#define MUSIC_PAT_FILE         "MUSIC.PAT"
#define MUSIC_PAT_HEADER_BYTES 512
#define MUSIC_PAT_SLOT_BYTES   4096
#define MUSIC_PAT_SECTOR       2048

/*----------------------
 | MUSIC_SYNTH_TRACK_MIN / MUSIC_SYNTH_TRACK_MAX
 | Description: The CD-DA track numbers music_synth_song_for_track answers for.
 |   They are the disc's own range, so a caller can hand it whatever the room
 |   table named without checking first.
 | Author: suinevere
 ----------------------*/
#define MUSIC_SYNTH_TRACK_MIN 2
#define MUSIC_SYNTH_TRACK_MAX 32

/*----------------------
 | music_synth_song_count
 | Description: How many tunes the build carries.
 | Author: suinevere
 | Dependencies: N/A
 | Globals: N/A
 | Params: N/A
 | Returns: MUSIC_SYNTH_SONGS
 ----------------------*/
int music_synth_song_count(void);

/*----------------------
 | music_synth_song_at
 | Description: One tune by index. An index outside the catalogue returns the
 |   default rather than nothing, because a bad index should sound like the
 |   wrong tune and not like a silent build.
 | Author: suinevere
 | Dependencies: tracker.h
 | Globals: N/A
 | Params: index -- 0..MUSIC_SYNTH_SONGS-1
 | Returns: a song valid for the life of the program
 ----------------------*/
const TrackerSong *music_synth_song_at(int index);

/*----------------------
 | music_synth_pairs
 | Description: The catalogue's (note, wv) pair table, which every cell in both
 |   the linked tunes and the ones on /BG/MUSIC.PAT is an index into.
 | Author: suinevere
 ----------------------*/
const TrackerPair *music_synth_pairs(void);

/*----------------------
 | music_synth_song_name
 | Description: A tune's title, for anything that shows the player what is
 |   playing.
 | Author: suinevere
 | Dependencies: N/A
 | Globals: N/A
 | Params: index -- 0..MUSIC_SYNTH_SONGS-1
 | Returns: a string valid for the life of the program
 ----------------------*/
const char *music_synth_song_name(int index);

/*----------------------
 | MUSIC_SYNTH_ID_MAX
 | Description: The longest id, so a caller can reserve a column for one. The
 |   Sound page's Test Track row is why this exists: it has 12 columns of value
 |   after a padded label, which an id fits and a title does not.
 | Author: suinevere
 ----------------------*/
#define MUSIC_SYNTH_ID_MAX 12

/*----------------------
 | music_synth_song_id
 | Description: A tune's short name -- its id in songs.json, which is what the
 |   preview scripts take on the command line and what a menu row has room for.
 |   The title is music_synth_song_name.
 | Author: suinevere
 | Dependencies: N/A
 | Globals: N/A
 | Params: index -- 0..MUSIC_SYNTH_SONGS-1
 | Returns: a string valid for the life of the program
 ----------------------*/
const char *music_synth_song_id(int index);

/*----------------------
 | music_synth_song_for_track
 | Description: Which tune stands in for a CD-DA track. The table is measured
 |   by tools/gen_synth_moods.py -- each of the disc's tracks matched to the
 |   tune that measures nearest to it -- so a room that names a track gets the
 |   closest thing the synth has rather than the same loop everywhere.
 | Author: suinevere
 | Dependencies: N/A
 | Globals: N/A
 | Params: track -- a CD-DA track number
 | Returns: a song index, the default for a track outside the disc's range
 ----------------------*/
int music_synth_song_for_track(int track);

/*----------------------
 | music_synth_song
 | Description: The default tune. Kept so callers that only ever wanted "the
 |   music" do not have to name one.
 | Author: suinevere
 | Dependencies: tracker.h
 | Globals: N/A
 | Params: N/A
 | Returns: a song valid for the life of the program
 ----------------------*/
const TrackerSong *music_synth_song(void);

#ifdef __cplusplus
}
#endif
#endif /* MUSIC_SYNTH_DATA_H */
