/*----------------------
 | synth.c
 | Description: Implementation of the voice layer. The FNS table is Sega's,
 |   from the SCSP User's Manual 4.2.5 -- twelve values covering one octave,
 |   with OCT carrying the rest.
 | Author: suinevere
 | Dependencies: synth.h, scsp.h
 ----------------------*/
#include "synth.h"
#include "scsp.h"

/*----------------------
 | SYNTH_WAVE_TABLE
 | Description: The band-limited waveform tables, generated offline by
 |   tools/assets/genwaves.py into synth_waves.c.
 | Author: suinevere
 ----------------------*/
extern const signed char SYNTH_WAVE_TABLE[4][SCSP_WAVE_MAX];

/*----------------------
 | SYNTH_NOISE_TABLE
 | Description: The percussion waveform, generated by the same script. Separate
 |   from SYNTH_WAVE_TABLE because it is a different length.
 | Author: suinevere
 ----------------------*/
extern const signed char SYNTH_NOISE_TABLE[SCSP_NOISE_LEN];

/*----------------------
 | SYNTH_FNS
 | Description: Sega's published FNS value per semitone, C through B.
 | Author: suinevere
 ----------------------*/
static const unsigned short SYNTH_FNS[12] = {
    0x000, 0x03D, 0x07D, 0x0C2, 0x10A, 0x157,
    0x1A8, 0x1FE, 0x25A, 0x2BA, 0x321, 0x38D
};



unsigned short synth_pitch(int semitone, int octave) {
    if (semitone < 0) semitone = 0;
    if (semitone > 11) semitone = 11;
    if (octave < -8) octave = -8;
    if (octave > 7) octave = 7;
    return (unsigned short)(((unsigned)(octave & 0x0F) << 11) | SYNTH_FNS[semitone]);
}

void synth_wave_build(int index, signed char *out, int len) {
    int i;
    if (index < 0 || index >= SCSP_NOISE_WAVE) index = 0;
    for (i = 0; i < len; i++)
        out[i] = SYNTH_WAVE_TABLE[index][(i * SCSP_WAVE_MAX) / len % SCSP_WAVE_MAX];
}

#include "tracker.h"
#include "music_synth_data.h"
#include "song_bank.h"

static int g_level = 7;
static int g_voice_vol[SCSP_VOICES];
static int g_voice_on[SCSP_VOICES];

/*----------------------
 | g_song / g_paused
 | Description: Which tune is loaded and whether the tick is being withheld.
 |   g_song is remembered rather than read back off the tracker because the
 |   tracker knows a song by its address and the callers name one by index, and
 |   because synth_start_song has to be able to tell "this tune again" from "a
 |   different tune" without comparing pointers into generated data.
 | Author: suinevere
 ----------------------*/
static int g_song = MUSIC_SYNTH_DEFAULT;
static int g_paused = 0;

void synth_note_on(int channel, int semitone, int octave, int wave, int vol) {
    if (channel < 0 || channel >= SCSP_VOICES) return;
    if (semitone < 0) {
        scsp_key_off(channel);
        g_voice_on[channel] = 0;
        return;
    }
    g_voice_vol[channel] = vol;
    g_voice_on[channel] = 1;
    scsp_key_on(channel, synth_pitch(semitone, octave), wave,
                (vol * g_level) / 7, wave == SCSP_NOISE_WAVE);
}

void synth_bind(volatile unsigned short *regs, volatile signed char *wave_ram, unsigned long wave_sa) {
    scsp_bind(regs, wave_ram, wave_sa);
}

void synth_init(void) {
    scsp_silence();
    /* Uploaded straight from the tables rather than through synth_wave_build:
       the percussion waveform is 4 KB and a stack buffer that size is not
       something to put on the Saturn's 32 KB of stack. */
    for (int w = 0; w < SCSP_NOISE_WAVE; w++)
        scsp_upload_wave(w, SYNTH_WAVE_TABLE[w], SCSP_WAVE_MAX);
    scsp_upload_wave(SCSP_NOISE_WAVE, SYNTH_NOISE_TABLE, SCSP_NOISE_LEN);
    for (int v = 0; v < SCSP_VOICES; v++) {
        g_voice_vol[v] = 0;
        g_voice_on[v] = 0;
    }
}

void synth_start(void) {
    synth_start_song(MUSIC_SYNTH_DEFAULT);
}

void synth_start_song(int index) {
    const TrackerSong *song;
    if (index < 0 || index >= song_bank_count()) index = MUSIC_SYNTH_DEFAULT;
    if (index == g_song && tracker_playing() && !g_paused) return;
    /* Stopped BEFORE the song is fetched, not after. On the CD build a tune the
       image does not carry is read off the disc into a buffer the tracker may
       be walking at that moment -- synth_tick runs on the V-blank -- so asking
       for it while the tracker is live is a read under a reader. */
    tracker_stop();
    song = song_bank_at(index);
    g_song = index;
    g_paused = 0;
    tracker_start(song, synth_note_on);
}

int synth_song(void) {
    return g_song;
}

int synth_song_count(void) {
    return song_bank_count();
}

void synth_play_track(int track, int loop) {
    (void)loop;
    if (track <= 0) { synth_stop(); return; }
    synth_start_song(song_bank_for_track(track));
}

int synth_track_is_short(int track) {
    (void)track;
    return 0;
}

void synth_stop(void) {
    tracker_stop();
    g_paused = 0;
    for (int v = 0; v < SCSP_VOICES; v++) {
        scsp_key_off(v);
        g_voice_on[v] = 0;
    }
}

void synth_pause(void) {
    if (g_paused) return;
    g_paused = 1;
    for (int v = 0; v < SCSP_VOICES; v++) {
        scsp_key_off(v);
        g_voice_on[v] = 0;
    }
}

void synth_resume(void) {
    g_paused = 0;
}

void synth_set_level(int level) {
    if (level < 0) level = 0;
    if (level > 7) level = 7;
    g_level = level;
    for (int v = 0; v < SCSP_VOICES; v++)
        if (g_voice_on[v]) scsp_set_voice_level(v, (g_voice_vol[v] * g_level) / 7);
}

void synth_tick(void) {
    if (g_paused) return;
    tracker_tick();
}

int synth_playing(void) {
    return tracker_playing();
}

int synth_should_play(int has_cd_audio) {
    return has_cd_audio ? 0 : 1;
}
