"""English picker vocabulary for Zork I (Saturn), in the game's native order
(pointer table @0x0607cf6c). Index position must be preserved so a matched word maps
to the correct object downstream. Extracted from a runtime save state; 326 words."""
PICKER_WORDS = [
    'zzmgck',
    'zorkmid',
    'zork',
    'yellow button',
    'yellow',
    'wrist',
    'wrench',
    'word of the prayer',
    'wooden railing',
    'wooden ladder',
    'wooden door',
    'wing',
    'window',
    'white wall',
    'white house',
    'west',
    'water level',
    'water',
    'wall',
    'viscous material',
    'vampire bat',
    'vampire',
    'valve',
    'valuables',
    'up a tree',
    'tube',
    'trunk of jewels',
    'trunk',
    'trophy case',
    'troll',
    'trident',
    'trees',
    'tree',
    'treasure room',
    'treasure',
    'trap door',
    'tour guidebook',
    'torch',
    'tools',
    'tomb',
    'timber',
    'thief',
    'temple',
    'teeth',
    'tan label',
    'table',
    'sword',
    'switch',
    'surrounding wall',
    'stream',
    'stone door',
    'stone barrow',
    'stone',
    'stiletto',
    'stairs',
    'southwest',
    'southeast',
    'south',
    'songbird',
    'snack',
    'small window',
    'small valve',
    'pile of coal',
    'small mailbox',
    'sluice gates',
    'slag',
    'skull',
    'skin',
    'skeleton key',
    'skeleton',
    'silver',
    'shovel',
    'shore',
    'shin',
    'seaman',
    'screwdriver',
    'sceptre',
    'scarab',
    'sapphire',
    'sandy beach',
    'sandwich',
    'sand',
    'sailor',
    'sack',
    'rusty knife',
    'rug',
    'rope',
    'rocks',
    'river',
    'reservoir',
    'red tape processors',
    'red button',
    'red buoy',
    'red',
    'rainbow',
    'railing',
    'rail',
    'punctured boat',
    'punc boat',
    'pump',
    'pseudo',
    'previous adventurers',
    'preparation of food',
    'prayers',
    'pot of gold',
    'pot',
    'platinum bar',
    'platinum',
    'plastic',
    'pipe',
    'pines',
    'pillar',
    'pile of plastic',
    'pile of leaves',
    'pile of bodies',
    'pedestal',
    'pdp10',
    'path',
    'paste',
    'passage',
    'part',
    'parson',
    'parchment',
    'paper',
    'panel',
    'pair of hand',
    'painting',
    'paint',
    'page',
    'over your head',
    'old engravings',
    'odor',
    'number',
    'northwest',
    'northeast',
    'north',
    'nose',
    'nest',
    'neglected genius',
    'neck',
    'nail',
    'mouth',
    'mountains',
    'mountain',
    'mirror',
    'metal',
    'matchbook',
    'match',
    'marble pedestal',
    'marble',
    'map',
    'manual',
    'mailbox',
    'magic boat',
    'magic',
    'machine',
    'lurking grue',
    'lung power',
    'lung',
    'lunch',
    'locky ledge',
    'lights',
    'light',
    'lid',
    'leaves',
    'leather bag',
    'leak',
    'leaflet',
    'leaf',
    'large emerald',
    'large egg',
    'large bag',
    'lantern',
    'lamp',
    'lake',
    'ladder',
    'label',
    'knife',
    'kitchen window',
    'kitchen table',
    'kitchen',
    'key',
    'jeweled scarab',
    'jewel',
    'jade figurine',
    'ivory',
    'iron chain',
    'insect',
    'huge diamond',
    'house',
    'hope',
    'head',
    'gunk',
    'guide',
    'group of tool chests',
    'ground',
    'green bubble',
    'grating',
    'granite wall',
    'granite',
    'golden clockwork canary',
    'gold',
    'gods',
    'glass bottle',
    'glass',
    'giant walls',
    'ghosts',
    'ghost',
    'gate',
    'gash',
    'gas',
    'garlic',
    'frobozz magic gunk company',
    'frobozz magic boat company',
    'frobozz',
    'force',
    'fork',
    'forest path',
    'forest',
    'food',
    'foobar',
    'floor',
    'flame',
    'figurine',
    'fiends',
    'eye',
    'engravings',
    'end',
    'enameled',
    'emerald',
    'egyptian',
    'egg',
    'eating',
    'east',
    'dryer',
    'driver',
    'draft',
    'down',
    'door',
    'dome',
    'diamond',
    'desk',
    'dam',
    'cyclops',
    'cup',
    'crystal trident',
    'crystal skull',
    'crystal',
    'crack',
    'color',
    'coins',
    'coin',
    'coffin',
    'coal gas',
    'coal',
    'clothes dryer',
    'cliff',
    'chute',
    'chimney',
    'chasm',
    'channel',
    'chalice',
    'chain',
    'ceiling',
    'case',
    'carpet',
    'canvas',
    'candles',
    'candle',
    'canary',
    'button',
    'buoy',
    'bug',
    'bubble',
    'brown sack',
    'brown button',
    'brown',
    'broken timber',
    'broken lantern',
    'broken clockwork canary',
    'bridge',
    'brass lantern',
    'brass bell',
    'brass bauble',
    'branch',
    'black book',
    'bracelet',
    'box',
    'bottle',
    'bones',
    'bone',
    'board',
    'booklet',
    'book',
    'bolt',
    'boat',
    'boarded window',
    'blue button',
    'blue',
    'blow',
    'bloody axe',
    'blessings',
    'blade',
    'bird',
    'bell',
    'beetle',
    'beautiful brass bauble',
    'beak',
    'beach',
    'bauble',
    'bat',
    'basket',
    'barrow of stone',
    'barrow',
    'bar',
    'bag',
    'axe',
    'attic',
    'art',
    'ancient parchment',
    'ancient map',
    'altar',
    'air pump',
    'airpump',
    'air',
    'adventurers',
]
