# -*- coding: utf-8 -*-
"""English->JP maps for the picker word-by-word shim (noun+particle+verb, JP order).
NOUNS 79 (resolver table 0x0607c9bc), VERBS 183 (inverted zork_en2reading.VERBS),
PARTICLES 11 (PREP_PARTICLE + obj-particle を). Assemble in place: JP[noun]+JP[particle]+JP[verb]."""
NOUNS = {
    'altar': '祭壇',
    'axe': '斧',
    'bar': '棒',
    'barrow': '塚',
    'basket': '篭',
    'board': '板',
    'body': '死体',
    'book': '本',
    'candles': 'ろうそく',
    'carving': '刻み',
    'chalice': '杯',
    'chimney': '煙突',
    'cliff': '絶壁',
    'coal': '石炭',
    'coffin': '棺',
    'crack': '裂け目',
    'crystal': '水晶',
    'door': '扉',
    'egg': '卵',
    'forest': '林',
    'ghost': '幽霊',
    'glue': '接着剤',
    'gold': '金',
    'ground': '地面',
    'hands': '両手',
    'house': '家',
    'key': '鍵',
    'kitchen': '台所',
    'knife': '刃物',
    'ladder': '梯子',
    'leaflet': 'ぱんふれっと',   # NOT 説明書(0x0256): leaflet object binds ぱんふれっと(0x01f9). 説明書 parses but no in-scope object carries it -> "you cannot see that here". せつめいしょ(0x025e) collides with mailbox.
    'leak': 'ボートの穴',
    'leaves': '落葉',
    'magic': '魔法',
    'mailbox': '郵便箱',
    'map': '地図',
    'match': '紙マッチ',
    'mirror': '鏡',
    'mountain': '山脈',
    'nest': '巣',
    'painting': '美術品',
    'paper': '紙',
    'passage': '通路',
    'path': '道',
    'pedestal': '台座',
    'pot': '壷',
    'prayer': '祈りの言葉',
    'pump': '空気ポンプ',
    'rainbow': '虹',
    'reservoir': '貯水池',
    'river': '川',
    'rug': 'じゅうたん',
    'sack': '袋',
    'sailor': '船のり',
    'sand': '砂',
    'scarab': 'こがねむし',
    'silver': '銀',
    'skeleton': '骸骨',
    'skull': '頭蓋骨',
    'slide': 'すべり台',
    'smelly': '臭い',
    'songbird': '青い鳥',
    'staircase': '階段',
    'stiletto': '短剣',
    'stone': '石',
    'stream': '小川',
    'sword': '剣',
    'teeth': '歯',
    'thief': '強盗',
    'timber': '木材',
    'tool': '道具箱',
    'torch': 'たいまつ',
    'toy': 'おもちゃ',
    'treasure': '財宝',
    'tree': '木',
    'wall': '壁',
    'water': '水',
    'window': '窓',
}

# Compass / movement directions -> bare JP reading (NO を particle). Readings validated against
# ZVOCTBL (flag 0x10 direction) in zork_en2reading.DIRECTIONS. A direction parses standalone; the
# movement verb (go/walk/run) is elided (see MOVEMENT_VERBS). Long forms first, then short forms
# (the word-by-word matcher requires an exact word boundary, so 'n' never shadows 'north').
DIRECTIONS = {
    'north': 'きた', 'south': 'みなみ', 'east': 'ひがし', 'west': 'にし',
    'up': 'うえ', 'down': 'した',
    'northeast': 'ほくとう', 'northwest': 'ほくせい', 'southeast': 'なんとう', 'southwest': 'なんせい',
    'n': 'きた', 's': 'みなみ', 'e': 'ひがし', 'w': 'にし', 'u': 'うえ', 'd': 'した',
    'ne': 'ほくとう', 'nw': 'ほくせい', 'se': 'なんとう', 'sw': 'なんせい',
}

# Movement verbs elided to empty; the verb is instead BAKED into each direction token (see
# MOVE_VERB) because this engine rejects a bare direction ("no verb" error) and needs a movement
# verb, exactly like its own menu emits "GO NORTH". enter/exit/go-in/go-out stay their own verbs.
MOVEMENT_VERBS = ['go', 'walk', 'run', 'head', 'proceed']

# Go-verb appended after a direction to form a complete movement command in Japanese SOV order
# ("go west" -> にし + 行く = にし行く), matching the working picker pattern (noun + verb).
MOVE_VERB = '行く'

VERBS = {
    'add': '加える',
    'answer': '答える',
    'apply': '塗る',
    'ask': '聞く',
    'attack': '攻撃する',
    'be loud': 'うるさい',
    'blast': '爆破する',
    'block': '塞ぐ',
    'blow in': '吹き込む',
    'blow out': '吹き消す',
    'blow up': '膨らませる',
    'board': '乗り込む',
    'break': '壊す',
    'breathe': '呼吸する',
    'budge': '動かす',
    'burn': '火を灯す',
    'burn up': '燃やす',
    'call': '呼ぶ',
    'carve': '刻む',
    'cast': '呪文を唱える',
    'chase': '追う',
    'clean': 'きれいにする',
    'climb': '登る',
    'close': '閉める',
    'coil': '巻く',
    'command': '命令する',
    'count': '数える',
    'cross': '横切る',
    'curse': 'ののしる',
    'cut': '切る',
    'damn': '呪う',
    'defeat': 'やっつける',
    'deflate': '空気を抜く',
    'descend': '降りる',
    'destroy': '破壊する',
    'detach': 'はずす',
    'devour': 'むしゃむしゃ食べる',
    'dig': '掘る',
    'discard': '捨てる',
    'disenchant': '魔法を解く',
    'douse': '水をかける',
    'drink': '飲む',
    'drop': '落とす',
    'eat': '食べる',
    'enchant': '魔法をかける',
    'enter': '中に入る',
    'examine': '調べる',
    'exit': '外に出る',
    'exorcise': '悪魔払いをする',
    'extinguish': '消す',
    'feel': '触れる',
    'fill': 'いっぱいにする',
    'fill up': '満たす',
    'find': '見つける',
    'flip': 'めくる',
    'free': '自由にする',
    'give': '与える',
    'go': '行く',
    'go across': '渡る',
    'go in': '入る',
    'go out': '出る',
    'grip': '握る',
    'hand': '渡す',
    'hit': '打つ',
    'hoist': '引き上げる',
    'hold up': '掲げる',
    'hop': '跳ねる',
    'hug': '抱きしめる',
    'hurt': '傷つける',
    'ignite': '火をつける',
    'illuminate': '点灯する',
    'inflate': '空気を入れる',
    'insert': '入れる',
    'jump': '跳ぶ',
    'jump over': '跳び越える',
    'kick': '蹴る',
    'kill': '殺す',
    'kindle': '灯す',
    'kiss': 'キスする',
    'knock': 'ノックする',
    'land': '上陸',
    'launch': '進水',
    'lean': '寄りかかる',
    'leap': '跳び越す',
    'leave': '去る',
    'let down': '下げる',
    'lift': '持ち上げる',
    'light': 'あかりをつける',
    'lock': '鍵を掛ける',
    'lock up': 'ロックする',
    'look': '見る',
    'look around': '見回す',
    'look down': '見下ろす',
    'look under': '下を覗く',
    'look up': '見上げる',
    'lower': '下ろす',
    'make': '作る',
    'melt': '溶かす',
    'mount': '上に乗る',
    'move': '移動する',
    'mutter': 'つぶやく',
    'open': '開ける',
    'open up': '開く',
    'order': '命じる',
    'pass': '通る',
    'peek': '覗く',
    'peer': '覗き込む',
    'pet': 'なでる',
    'pick up': '拾う',
    'pierce': '突き刺す',
    'play': '演じる',
    'plug': '栓をする',
    'poke': '突く',
    'polish': '磨く',
    'pour': '注ぐ',
    'pray': '祈る',
    'prod': 'つつく',
    'pry': 'こじ開ける',
    'pull': '引く',
    'puncture': 'パンクさせる',
    'push': '押す',
    'put': '置く',
    'raise': '上げる',
    'react': '応答する',
    'read': '読む',
    'remove': '取り出す',
    'repent': '後悔する',
    'reply': '返事する',
    'respond': '返答する',
    'retreat': '後退する',
    'ride': '乗る',
    'ring': '鳴らす',
    'rob': '強奪する',
    'rock': '揺らす',
    'roll': '転がす',
    'rotate': '回す',
    'rub': 'こする',
    'say': '言う',
    'scream': '叫ぶ',
    'search': '捜す',
    'seize': '奪う',
    'set afloat': '水に降ろす',
    'shake': '振る',
    'shift': 'ずらす',
    'shout': '大声をあげる',
    'shut': '閉じる',
    'sit': '座る',
    'skip': 'スキップする',
    'smell': '臭いをかぐ',
    'snatch': '取り上げる',
    'sniff': '臭う',
    'spray': 'スプレーする',
    'spritz': 'ふきかける',
    'stab': '刺す',
    'stand': '立つ',
    'stay': '滞在する',
    'swim': '泳ぐ',
    'swim across': '泳いで渡る',
    'swing': '振り上げる',
    'take': '取る',
    'talk': '話す',
    'tap': 'たたく',
    'tell': '告げる',
    'throw': '投げる',
    'tie': '結ぶ',
    'touch': '触る',
    'tug': '引っ張る',
    'turn': '振り向く',
    'turn around': '振り返る',
    'turn on': '点ける',
    'undo lock': '鍵をはずす',
    'unlock': '鍵を開ける',
    'untie': 'ほどく',
    'wait': '待つ',
    'wake': '起こす',
    'walk': '歩く',
    'wander': '歩き回る',
    'wave': '振り回す',
    'win': '勝つ',
    'wind': 'ぜんまいを巻く',
    'wind up': 'ねじを巻く',
    'wish': '望む',
    'yell': 'どなる',
}

PARTICLES = {
    'and': 'を',
    'at': 'に',
    'from': 'から',
    'in': 'を',
    'inside': 'に',
    'into': 'に',
    'on': 'に',
    'onto': 'に',
    'under': 'の下',
    'using': 'で',
    'with': 'で',
}

